### ISSUE TITLE
Blakefiler

### ISSUE THREAD

**Issue by jart** [tmandry/lavender#2]
This might interest you.

- https://youtu.be/gQidLhPVn70
- https://gist.github.com/jart/082b1078a065b79949508bbe1b7d8ef0

**Comment by tmandry** [comment]
Very cool! I would support a `bazel dist` or something similar one day. Going to CMake makes sense, but a Makefile is very clean and doesn't require extra tools. I guess CMake could be leveraged for its detection of compilers.

Added this to "Related projects" section.

**Comment by jart** [comment]
I'm kind of agnostic to tooling and I'm happy with whatever, so long as it builds and meets requirements without too much fuss. Out of curiosity, as someone who knows more about Windows development than me, what's your take on https://github.com/richfelker/musl-cross-make and https://midipix.org/? I've heard rumors that if we combine Musl and Midipix, we can have native POSIX on Windows without Cygwin or MinGW or DLLs or anything like that.

**Comment by tmandry** [comment]
@jart I'm not that knowledgeable about it actually 😄 I created this to help transition my team to bazel, and some of them are avid users of Visual Studio.

Regarding Musl/Midipix, that sounds great. It would definitely simplify a lot of things. Right now our codebase uses lots of `#ifdef`s and some features/applications only work on Linux. Cygwin/Msys2 are okay but there are a lot of papercuts / things that don't work as expected..
